config/routes.rb
Autoportal::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  resources :marks, :advertisements

  root :to => "home#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    @user = user
    send(@user.role) if @user
  end

  def admin
    can :manage, Mark
    can :manage, Advertisement
    can :manage, User

    #Admin panel ability
    can :access, :rails_admin
    can :dashboard
  end

  def user
    can :read, Advertisement
    can :manage, User, :id => @user.id
  end
end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
  attr_accessible :advertisementable_id, :advertisementable_type, :created_by_id, :paid, :paid_at, :title
end

app/models/car_value.rb
class CarValue < ActiveRecord::Base
  attr_accessible :car_values, :option
  serialize :car_values, Array
  validates :option, presence: true, uniqueness: true

  scope :for, lambda { |option| where(option: option) }

  def self.options(option)
    find_by_option(option).try(:car_values)
  end

end

app/models/mark.rb
class Mark < ActiveRecord::Base
  attr_accessible :name, :logo
  include Enumerize
  validates :name, :logo, presence: true

  has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  test_array = Rails.env.test? ? ['Ford', 'BMW', 'Audi'] : []

  enumerize :name, :in => CarValue.options('name') || test_array if CarValue.nil?
end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :body, :created_by_id, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  include Enumerize

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role
  # attr_accessible :title, :body
  enumerize :role, :in => %w[admin user], defaule: 'user'
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
	load_and_authorize_resource
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, :alert => exception.message
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  load_and_authorize_resource
end

app/helpers/application_helper.rb
module ApplicationHelper
	def alert_type(name)
 		if name == :alert
    	"error"
    else
    	"success"
    end		
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/views/advertisements/index.html.slim
p FFfff

p FFfff

p FFfff

p FFfff

p FFfff

p FFfff

p FFfff

p FFfff

p FFfff

app/views/home/index.html.erb
<h1>Blabla</h1>
<%= content_for :sidebar do %>
  sdgf
<% end %>

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Autoportal"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    link href="images/favicon.ico" rel="shortcut icon"
    link href="images/apple-touch-icon.png" rel="apple-touch-icon"
    link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"
    link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"

  body
    - flash.each do |name, msg|
      - name = alert_type(name) 
      div class="alert alert-#{name}"
        .close data-dismiss="alert" ×
        =msg
    .navbar
      .navbar-inner
        .container
          a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to 'Autoportal', root_path, class: :brand
          .container.nav-collapse
            = render_navigation :expand_all => true, :renderer => :bootstrap


    .container

      .content
        .row
          .span8
            = yield
          .span3
            - if content_for?(:sidebar)
              div= yield(:sidebar)

      footer
        p &copy; Company 2012
    /!
      Javascripts
      \==================================================
    /! Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/marks/_form.html.slim
= form_for @mark do |f|
  - if @mark.errors.any?
    #error_explanation
      h2 = "#{pluralize(@mark.errors.count, "error")} prohibited this mark from being saved:"
      ul
        - @mark.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit 'Save'

app/views/marks/edit.html.slim
h1 Editing mark

== render 'form'

= link_to 'Show', @mark
'|
= link_to 'Back', marks_path

app/views/marks/index.html.slim
h1 Listing marks

table
  tr
    th Name
    th
    th
    th

  - @marks.each do |mark|
    tr
      td = mark.name
      td = link_to 'Show', mark
      td = link_to 'Edit', edit_mark_path(mark)
      td = link_to 'Destroy', mark, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Mark', new_mark_path

app/views/marks/new.html.slim
h1 New mark

== render 'form'

= link_to 'Back', marks_path

app/views/marks/show.html.slim
p#notice = notice

p
  strong Name:
  = @mark.name

= link_to 'Edit', edit_mark_path(@mark)
'|
= link_to 'Back', marks_path